name: Go

on:
  pull_request:
    branches:
      - main
      - develop

      

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      STRIPE_API_KEY: ${{ secrets.STRIPE_API_KEY}}
      
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21.2"

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v -cover ./...

      - name: Github stuff
        run: echo "My repo name is ${{github.repository}}"  
